INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_FIRST_NAME , AUTHOR_LAST_NAME ) VALUES (1, 'Steve', 'Jobs');
INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_FIRST_NAME , AUTHOR_LAST_NAME ) VALUES (2, 'Phil', 'Knight');
INSERT INTO BOOK_ARTIST  (ID, ARTISTS_ID    , BOOK_ID    ) VALUES   (1, '1', '1');
INSERT INTO BOOK_ARTIST  (ID, ARTISTS_ID   ,BOOK_ID    ) VALUES    (2, '2', '2');
INSERT INTO BOOK (BOOK_ID, BOOK_ISBN  , BOOK_PAGE_COUNT ,BOOK_TITLE  ) VALUES  (1,'12345',20, 'Steve Jobs');
INSERT INTO BOOK (BOOK_ID,BOOK_ISBN  , BOOK_PAGE_COUNT ,BOOK_TITLE  ) VALUES (2, '56789', 20, 'Shoe Dog');